import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { extname, join } from 'node:path';

for (const file of [
  'app/page.tsx',
  'components/AtlasClient.tsx',
  'lib/atlas.ts',
  'app/api/weather/route.ts',
  'app/api/spatial/sample/route.ts',
  'app/api/gbif/observations/route.ts',
  'app/api/conservation/screen/route.ts',
  'docs/data-engine.md'
]) {
  assert.ok(existsSync(file), `missing ${file}`);
}

const atlas = readFileSync('lib/atlas.ts', 'utf8');
for (const taxon of [
  'Craterellus cornucopioides',
  'Macrolepiota procera',
  'Sparassis crispa',
  'Calvatia gigantea'
]) {
  assert.ok(atlas.includes(taxon));
}

assert.ok(atlas.includes("'PHOTO_ONLY'"));
assert.ok(!existsSync('pyproject.toml'));
assert.ok(!existsSync('bin/compact'));
assert.ok(!readFileSync('README.md', 'utf8').startsWith('# compact-dev'));
assert.ok(!existsSync('next-env.d.ts'), 'next-env.d.ts is generated by Next.js and must not be committed');

for (const root of ['app', 'components', 'lib']) {
  const stack = [root];
  while (stack.length) {
    const dir = stack.pop();
    if (!dir) continue;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(path);
        continue;
      }
      const extension = extname(entry.name);
      assert.ok(extension === '.ts' || extension === '.tsx', `non-TypeScript source file in ${path}`);
    }
  }
}

console.log('Pilzatlas repository invariants: OK');
