import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { extname, join } from 'node:path';

for (const file of [
  'app/page.tsx',
  'components/AtlasClient.tsx',
  'lib/atlas.ts',
  'app/api/weather/route.ts',
  'app/api/spatial/sample/route.ts',
  'app/api/gbif/observations/route.ts',
  'app/api/conservation/screen/route.ts',
  'docs/data-engine.md'
]) {
  assert.ok(existsSync(file), `missing ${file}`);
}

const atlas = readFileSync('lib/atlas.ts', 'utf8');
for (const taxon of [
  'Craterellus cornucopioides',
  'Macrolepiota procera',
  'Sparassis crispa',
  'Calvatia gigantea'
]) {
  assert.ok(atlas.includes(taxon));
}

assert.ok(atlas.includes("'PHOTO_ONLY'"));
assert.ok(!existsSync('pyproject.toml'));
assert.ok(!existsSync('bin/compact'));
assert.ok(!readFileSync('README.md', 'utf8').startsWith('# compact-dev'));

let nextEnvTracked = true;
try {
  execFileSync('git', ['ls-files', '--error-unmatch', 'next-env.d.ts'], { stdio: 'ignore' });
} catch {
  nextEnvTracked = false;
}
assert.ok(!nextEnvTracked, 'next-env.d.ts is generated by Next.js and must not be committed');

const forbiddenSourceExtensions = new Set(['.js', '.jsx', '.mjs', '.cjs']);
for (const root of ['app', 'components', 'lib']) {
  const stack = [root];
  while (stack.length) {
    const dir = stack.pop();
    if (!dir) continue;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(path);
        continue;
      }
      assert.ok(
        !forbiddenSourceExtensions.has(extname(entry.name)),
        `JavaScript source file found where TypeScript is required: ${path}`
      );
    }
  }
}

console.log('Pilzatlas repository invariants: OK');
